import React, { useState, useEffect, useRef, useMemo } from 'react';
import {
    Zap, ScanLine, Microscope, AlertCircle, Check, X,
    ChevronDown, ListChecks, Sparkles, Play, Square,
    Pause, RotateCcw, PenTool, LayoutTemplate, Bug, MousePointerClick, Bot,
    Settings as SettingsIcon, RefreshCw, Loader
} from 'lucide-react';
import { assessStudentAnswer, generateRubricFromImages, GradingStrategy, getAppConfig } from '@/services/geminiService';
import { gradeStudentAnswerStream } from '@/services/grading-stream';
import { isProxyMode, gradeWithProxy } from '@/services/proxyService';
import { useTheme } from '@/hooks/useTheme';
import AutoRubricModal from './AutoRubricModal';
import { StatusIndicator } from './ui/StatusIndicator';
import { toast } from './Toast';
import { Button } from './ui';
import RubricLibrary from './RubricLibrary';
import { addLocalRecord } from '@/services/record-sync';

// @ts-ignore - Vite 环境变量
const API_BASE_URL = (import.meta.env?.VITE_API_BASE_URL as string) || 'http://localhost:3000';



// --- Interfaces ---
export enum GradingMode {
    Assist = 'assist', // 辅助模式：批改后填分，等待用户确认后提交
    Auto = 'auto'      // 自动模式：批改后自动填分并提交
}

interface PageContext {
    studentName?: string;
    questionNo?: string;    // 从页面提取的题号
    questionKey?: string;   // 唯一标识 (platform + paperId + questionNo)
    markingPaperId?: string;
    examNo?: string;
    platform?: string;      // 'ZHIXUE' | 'HAOFENSHU' | 'UNKNOWN'
    answerImageBase64?: string; // 完整或合成后的图片
    answerChunksBase64?: string[]; // 分块图片（如果页面是切片的）
}

interface StudentResult {
    id: string;
    name: string;
    score: number;
    maxScore: number;
    comment: string;
    breakdown: Array<{
        label: string;
        score: number;
        max: number;
        comment?: string;
        isNegative?: boolean; // 是否为扣分项
    }>;
}

interface GradingViewProps {
    onOpenRubric: () => void;
    isRubricConfigured: boolean;
    currentRubric: string; // 只有在检测到题目并加载后才有值
    gradingStrategy: GradingStrategy;
    onQuestionKeyChange?: (key: string | null) => void;
    onSaveRubric?: (rubric: string) => void;
    configuredQuestions?: { key: string; questionNo: string; platform: string }[];
    onOpenSettings?: () => void;
    // 激活拦截相关
    usageInfo?: { used: number; limit: number; remaining: number };
    onShowActivation?: () => void;
}

type StatusType = 'idle' | 'scanning' | 'grading' | 'review' | 'error';

// Helper: Normalize Breakdown
const normalizeBreakdown = (raw: any[], maxScore: number) => {
    if (!Array.isArray(raw)) return [];
    return raw.map(item => ({
        label: item.label || '得分点',
        score: Number(item.score) || 0,
        max: Number(item.max) || 0,
        comment: item.comment || '',
        isNegative: item.isNegative || false
    }));
};

// Helper: Extract Signature
const getAnswerSignature = (base64: string | undefined) => {
    if (!base64 || base64.length < 100) return null;
    return base64.substring(base64.length - 200, base64.length - 100) + base64.length;
};

// --- Main Component ---
const GradingView: React.FC<GradingViewProps> = ({
    onOpenRubric,
    isRubricConfigured,
    currentRubric,
    gradingStrategy,
    onQuestionKeyChange,
    onSaveRubric,
    configuredQuestions = [],
    onOpenSettings,
    usageInfo,
    onShowActivation
}) => {
    // State
    const [status, setStatus] = useState<StatusType>('idle');
    const [result, setResult] = useState<StudentResult | null>(null);
    const [mode, setMode] = useState<GradingMode>(GradingMode.Assist);
    const [errorMsg, setErrorMsg] = useState<string | null>(null);
    const [waitCount, setWaitCount] = useState(0);
    const [autoCount, setAutoCount] = useState(0);
    const [streamingText, setStreamingText] = useState('');

    // Page Context
    const [pageContext, setPageContext] = useState<PageContext | null>(null);
    const [manualQuestionNo, setManualQuestionNo] = useState<string>('');

    // Health Check - 状态为 null 表示未检测
    const [health, setHealth] = useState<{ api: boolean | null, pageLink: boolean | null }>({
        api: null,
        pageLink: null
    });
    const [isDetecting, setIsDetecting] = useState(true);  // 是否正在检测
    const [detectingStep, setDetectingStep] = useState(0); // 0: API, 1: 页面, 2: 细则, 3: 完成
    const [detectedQuestionKey, setDetectedQuestionKey] = useState<string | null>(null);

    // Layout State
    const [showQuestionDropdown, setShowQuestionDropdown] = useState(false);
    const [isEditingScore, setIsEditingScore] = useState(false);
    const [editableScore, setEditableScore] = useState<number | null>(null);

    // Auto Rubric Generation
    const [showAutoRubricModal, setShowAutoRubricModal] = useState(false);
    const [isGeneratingRubric, setIsGeneratingRubric] = useState(false);
    const [autoGeneratedRubric, setAutoGeneratedRubric] = useState('');

    // 答题卡状态 (智学网专用)
    const [answerCardStatus, setAnswerCardStatus] = useState<{
        status: 'ready' | 'loading' | 'needRefresh' | 'noImage' | 'unknown';
        message: string;
    } | null>(null);

    // Refs for loop control
    const isAutoRunningRef = useRef(false);
    const isAssistLoopingRef = useRef(false);
    const [isAutoRunning, setIsAutoRunning] = useState(false);
    const [isAssistLooping, setIsAssistLooping] = useState(false);
    const abortScanRef = useRef(false);
    const lastGradedSignatureRef = useRef<string | null>(null);
    const assistAwaitingConfirmRef = useRef(false); // 辅助模式等待确认
    const [assistAwaitingConfirm, setAssistAwaitingConfirm] = useState(false);
    const [waitingRefresh, setWaitingRefresh] = useState(false); // 等待页面刷新
    const connectionErrorCountRef = useRef(0); // 连接错误计数器
    const MAX_CONNECTION_ERRORS = 15; // 增加到 15 次（约 30 秒），给页面刷新更多时间

    // Grading Animation Step
    const [gradingStep, setGradingStep] = useState(0);

    // Timing
    const [autoStartTime, setAutoStartTime] = useState<number | null>(null);
    const [elapsedSeconds, setElapsedSeconds] = useState(0);

    /**
     * 检查是否需要弹出激活界面
     * 触发条件：
     * 1. 额度用完 (remaining <= 0 且不是无限用户)
     * 注意：首次使用不再弹出激活界面，用户可直接免费使用
     */
    const checkActivationRequired = (): boolean => {
        console.log('[GradingView] checkActivationRequired called');
        console.log('[GradingView] usageInfo:', usageInfo);

        // 额度用完检查（非付费用户）
        if (usageInfo && usageInfo.remaining !== -1 && usageInfo.remaining <= 0) {
            console.log('[GradingView] ✓ Activation required: quota exhausted');
            return true;
        }

        console.log('[GradingView] ✗ Activation not required');
        return false;
    };

    // --- Effects ---

    // Timer for Auto Mode
    useEffect(() => {
        let timer: NodeJS.Timeout | undefined;
        if (isAutoRunning && autoStartTime) {
            timer = setInterval(() => {
                setElapsedSeconds(Math.floor((Date.now() - autoStartTime) / 1000));
            }, 1000);
        }
        return () => clearInterval(timer);
    }, [isAutoRunning, autoStartTime]);

    // Grading Animation
    useEffect(() => {
        let interval: NodeJS.Timeout | undefined;
        if (status === 'grading') {
            setGradingStep(0);
            interval = setInterval(() => {
                setGradingStep(prev => (prev + 1) % 4);
            }, 800);
        } else {
            setGradingStep(0);
        }
        return () => clearInterval(interval);
    }, [status]);

    // Content Script Communication Setup
    useEffect(() => {
        if (typeof chrome === 'undefined' || !chrome.runtime) return;

        const handleMessage = (message: { type: string; context?: PageContext }) => {
            if (message.type === 'PAGE_CONTEXT_UPDATE') {
                if (message.context) {
                    setPageContext(prev => ({ ...prev, ...message.context }));
                    setHealth(h => ({ ...h, pageLink: true }));

                    // Question Key logic - 优化：先按题号匹配已配置的细则
                    const pageQuestionNo = message.context.questionNo;
                    const pageQuestionKey = message.context.questionKey;

                    // 检测题号是否变化（用于自动清空并重新匹配）
                    const previousQuestionNo = pageContext?.questionNo;
                    const questionNoChanged = pageQuestionNo && previousQuestionNo && pageQuestionNo !== previousQuestionNo;

                    if (questionNoChanged) {
                        console.log('[GradingView] 检测到题号变化:', previousQuestionNo, '->', pageQuestionNo);
                        // 清空手动选择的题号，允许重新自动匹配
                        setManualQuestionNo('');
                        // 清空当前细则
                        setDetectedQuestionKey(null);
                        if (onQuestionKeyChange) onQuestionKeyChange(null);
                        toast.info(`已切换到第 ${pageQuestionNo} 题`);
                    }

                    // 功能1：题号自动匹配细则
                    if (pageQuestionNo && (!manualQuestionNo || questionNoChanged)) {
                        const matchedRubric = configuredQuestions.find(
                            q => q.questionNo === pageQuestionNo
                        );
                        if (matchedRubric && (matchedRubric.key !== detectedQuestionKey || questionNoChanged)) {
                            console.log('[GradingView] 自动匹配到细则:', matchedRubric.key);
                            setDetectedQuestionKey(matchedRubric.key);
                            setManualQuestionNo(matchedRubric.questionNo);
                            if (onQuestionKeyChange) onQuestionKeyChange(matchedRubric.key);
                            toast.success(`已自动匹配第 ${matchedRubric.questionNo} 题细则`);
                        } else if (!matchedRubric && questionNoChanged) {
                            // 无匹配细则，提示用户
                            toast.warning(`第 ${pageQuestionNo} 题暂无评分细则，请配置`);
                        }
                    }

                    // 原有逻辑：如果没有匹配到细则，使用页面的 questionKey
                    if (pageQuestionKey && pageQuestionKey !== detectedQuestionKey) {
                        // Only update if not manually overridden recently
                        if (!manualQuestionNo) {
                            setDetectedQuestionKey(pageQuestionKey);
                            if (onQuestionKeyChange) onQuestionKeyChange(pageQuestionKey);
                        }
                    }
                }
            } else if (message.type === 'PAGE_CONTEXT_LOST') {
                setHealth(h => ({ ...h, pageLink: false }));
            } else if (message.type === 'ANSWER_CARD_STATUS') {
                // 接收答题卡状态更新
                const msg = message as unknown as { type: string; status: string; message: string };
                setAnswerCardStatus({
                    status: msg.status as 'ready' | 'loading' | 'needRefresh' | 'noImage' | 'unknown',
                    message: msg.message
                });
                // 如果状态变为 ready，自动启动预检
                if (msg.status === 'ready' && !isDetecting) {
                    console.log('[GradingView] 答题卡就绪，自动启动预检');
                    checkSystemHealth();
                }
            } else if (message.type === 'AUTO_TASK_WAITING_REFRESH') {
                // 页面未自动跳转，需要刷新
                const msg = message as unknown as { type: string; message: string; waitCount: number; processed: number };
                console.log('[GradingView] 收到等待刷新消息:', msg.message, '已处理:', msg.processed);
                setWaitingRefresh(true);
                toast.warning('页面未自动跳转，请刷新阅卷界面');
            }
        };
        chrome.runtime.onMessage.addListener(handleMessage);

        // Initial Check
        checkSystemHealth();

        return () => chrome.runtime.onMessage.removeListener(handleMessage);
    }, [detectedQuestionKey, manualQuestionNo]);

    // Auto-reconnect: 当页面连接断开时，自动定期尝试重新连接
    // 无论是否在运行模式，都应该尝试重连
    const reconnectAttemptRef = useRef(0);
    const MAX_RECONNECT_ATTEMPTS = 20; // 最多尝试 20 次（约 40 秒）
    const wasRunningBeforeDisconnectRef = useRef(false); // 记录断开前是否在运行

    useEffect(() => {
        // 当页面连接断开时启动自动重连
        if (health.pageLink === false && !isDetecting) {
            // 记录断开前是否在运行（用于恢复后继续运行）
            if (isAutoRunning || isAssistLooping) {
                wasRunningBeforeDisconnectRef.current = true;
                console.log('[GradingView] 页面连接断开（运行模式），启动自动重连...');
            } else {
                wasRunningBeforeDisconnectRef.current = false;
                console.log('[GradingView] 页面连接断开（空闲模式），启动自动重连...');
            }

            const reconnectTimer = setInterval(async () => {
                reconnectAttemptRef.current += 1;
                console.log(`[GradingView] 自动重连尝试 ${reconnectAttemptRef.current}/${MAX_RECONNECT_ATTEMPTS}`);

                // 尝试 PING 页面
                if (typeof chrome !== 'undefined' && chrome.tabs) {
                    chrome.tabs.query({ active: true, currentWindow: true }, (tabs: chrome.tabs.Tab[]) => {
                        if (tabs[0]?.id) {
                            chrome.tabs.sendMessage(tabs[0].id, { type: 'PING' }, (res?: { success: boolean }) => {
                                if (!chrome.runtime.lastError && res?.success) {
                                    console.log('[GradingView] 自动重连成功');
                                    reconnectAttemptRef.current = 0;
                                    setHealth(h => ({ ...h, pageLink: true }));

                                    // 如果之前在运行模式，自动恢复扫描
                                    if (wasRunningBeforeDisconnectRef.current && (isAutoRunningRef.current || isAssistLoopingRef.current)) {
                                        console.log('[GradingView] 恢复运行模式，继续扫描...');
                                        connectionErrorCountRef.current = 0; // 重置错误计数
                                        setTimeout(() => scanPage({ forceStatusReset: true }), 500);
                                    } else {
                                        // 非运行模式，只触发系统检测
                                        checkSystemHealth();
                                    }
                                }
                            });
                        }
                    });
                }

                // 超过最大尝试次数后停止
                if (reconnectAttemptRef.current >= MAX_RECONNECT_ATTEMPTS) {
                    console.log('[GradingView] 自动重连达到最大尝试次数，停止重连');
                    clearInterval(reconnectTimer);
                    // 如果是在运行模式下超时，停止运行并提示
                    if (wasRunningBeforeDisconnectRef.current) {
                        setErrorMsg("页面连接超时，请刷新阅卷页面后重新开始");
                        setStatus('error');
                        stopAuto();
                    }
                }
            }, 2000); // 每 2 秒尝试一次

            return () => {
                clearInterval(reconnectTimer);
            };
        } else if (health.pageLink === true) {
            // 连接恢复，重置计数器
            reconnectAttemptRef.current = 0;
        }
    }, [health.pageLink, isDetecting]); // 移除 isAutoRunning 和 isAssistLooping 依赖

    // --- Core Functions ---

    const checkSystemHealth = async () => {
        setIsDetecting(true);
        setDetectingStep(0);

        // 延迟函数
        const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

        // Step 0: 检测 API 连接
        await delay(400);
        const cfg = getAppConfig();
        try {
            // 代理模式优先：检测后端是否可用
            const res = await fetch(`${API_BASE_URL}/api/health`);
            const data = await res.json();
            setHealth(prev => ({ ...prev, api: data?.success === true }));
        } catch {
            // 后端不可用，检查本地 API Key
            setHealth(prev => ({ ...prev, api: !!cfg.apiKey }));
        }
        setDetectingStep(1);

        // Step 1: 检测页面连接
        await delay(400);
        let pageConnected = false;
        if (typeof chrome !== 'undefined' && chrome.tabs) {
            await new Promise<void>((resolve) => {
                chrome.tabs.query({ active: true, currentWindow: true }, (tabs: chrome.tabs.Tab[]) => {
                    if (tabs[0]?.id) {
                        chrome.tabs.sendMessage(tabs[0].id, { type: 'PING' }, (res?: { success: boolean }) => {
                            if (chrome.runtime.lastError || !res?.success) {
                                setHealth(h => ({ ...h, pageLink: false }));
                            } else {
                                setHealth(h => ({ ...h, pageLink: true }));
                                pageConnected = true;
                            }
                            resolve();
                        });
                    } else {
                        setHealth(h => ({ ...h, pageLink: false }));
                        resolve();
                    }
                });
            });
        } else {
            setHealth(h => ({ ...h, pageLink: false }));
        }
        setDetectingStep(2);

        // Step 2: 检测评分细则 (由 isRubricConfigured prop 控制，这里只做动画延迟)
        await delay(400);
        setDetectingStep(3);

        // 完成检测后，如果页面连接成功，发送 CHECK_READY 触发答题卡高亮
        if (pageConnected && typeof chrome !== 'undefined' && chrome.tabs) {
            chrome.tabs.query({ active: true, currentWindow: true }, (tabs: chrome.tabs.Tab[]) => {
                if (tabs[0]?.id) {
                    chrome.tabs.sendMessage(tabs[0].id, { type: 'CHECK_READY' }, () => {
                        // 忽略响应，只是触发高亮
                        if (chrome.runtime.lastError) {
                            console.log('[GradingView] CHECK_READY 发送失败:', chrome.runtime.lastError);
                        }
                    });
                }
            });
        }

        // 完成检测
        await delay(200);
        setIsDetecting(false);
    };

    const getActiveTabId = async (): Promise<number | null> => {
        return new Promise((resolve) => {
            if (typeof chrome === 'undefined' || !chrome.tabs) return resolve(null);
            chrome.tabs.query({ active: true, currentWindow: true }, (tabs: chrome.tabs.Tab[]) => {
                resolve(tabs[0]?.id ?? null);
            });
        });
    };

    // --- Scanning & Grading Logic ---

    const scanPage = async (opts: { bypassLoopGuard?: boolean; forceStatusReset?: boolean } = {}) => {
        if (typeof chrome === 'undefined' || !chrome.tabs) return;

        if (!opts.bypassLoopGuard) {
            if (mode === GradingMode.Auto && !isAutoRunningRef.current) return;
            if (mode === GradingMode.Assist && !isAssistLoopingRef.current) return;
            // Assist mode pause check
            if (mode === GradingMode.Assist && assistAwaitingConfirmRef.current) return;
        }

        // Set status to scanning (force if forceStatusReset is true)
        if (opts.forceStatusReset || status !== 'scanning') {
            setStatus('scanning');
        }
        abortScanRef.current = false;

        const tabId = await getActiveTabId();
        if (!tabId) {
            setErrorMsg("无法连接到当前页面");
            setStatus('error');
            return;
        }

        // Send SCAN command (type must match content.js listener)
        chrome.tabs.sendMessage(tabId, { type: 'REQUEST_PAGE_DATA' }, async (response?: { success: boolean; data?: PageContext; error?: string; errorCode?: string }) => {
            // Debug: Log what we received
            console.log('[GradingView] REQUEST_PAGE_DATA response:', response);

            // Check for errors
            if (chrome.runtime.lastError || !response) {
                console.warn('[GradingView] No response or runtime error:', chrome.runtime.lastError);
                connectionErrorCountRef.current += 1;

                // 超过最大重试次数，提示用户刷新
                if (connectionErrorCountRef.current >= MAX_CONNECTION_ERRORS) {
                    setErrorMsg("页面连接已断开，请刷新阅卷页面后重试");
                    setStatus('error');
                    stopAuto();
                    return;
                }

                if (mode === GradingMode.Auto || mode === GradingMode.Assist) {
                    // Retry logic for loop modes
                    setWaitCount(c => c + 1);
                    setTimeout(() => scanPage(opts), 1000);
                } else {
                    setErrorMsg("页面连接断开，请刷新页面");
                    setStatus('error');
                }
                return;
            }

            // 连接成功，重置错误计数
            connectionErrorCountRef.current = 0;

            if (!response.success || !response.data) {
                // 检测是否是"无待阅试卷"特殊状态
                if (response.errorCode === 'NO_MORE_PAPERS') {
                    console.log('[GradingView] 无待阅试卷，停止自动阅卷');
                    setErrorMsg(response.error || '已无待阅试卷，批阅完成');
                    setStatus('idle'); // 不使用 error 状态，而是回到 idle 表示完成
                    if (mode === GradingMode.Auto) {
                        stopAuto();
                    } else {
                        stopAssist();
                    }
                    return;
                }

                // Valid response but no answer found (yet)
                console.log('[GradingView] Scan not successful:', response.error || 'No data');
                setWaitCount(c => c + 1);
                setTimeout(() => scanPage(opts), 1000); // Keep scanning
                return;
            }

            // Found Answer!
            setWaitCount(0);
            setWaitingRefresh(false); // 检测到新试卷，重置刷新等待状态
            const ctx: PageContext = response.data;
            setPageContext(ctx);

            // Duplicate Check
            const sig = getAnswerSignature(ctx.answerImageBase64);
            console.log('[GradingView] 图片签名:', sig?.substring(0, 30), '上次签名:', lastGradedSignatureRef.current?.substring(0, 30));
            if (sig && sig === lastGradedSignatureRef.current) {
                // Same paper, keep scanning for new one
                console.log('[GradingView] 检测到重复试卷，继续扫描...');
                setTimeout(() => scanPage(opts), 1000);
                return;
            }

            // Ready to Grade?
            // Check Rubric
            console.log('[GradingView] 评分标准检查 - isRubricConfigured:', isRubricConfigured, ', currentRubric长度:', currentRubric?.length || 0);
            if (!isRubricConfigured || !currentRubric) {
                // If no rubric, try auto-generate? (Only in manual mode interactions, not auto-loop)
                if (mode === GradingMode.Assist && !isAssistLoopingRef.current && !isGeneratingRubric && !showAutoRubricModal) {
                    // Prompt for auto-rubric
                    setShowAutoRubricModal(true);
                    generateAutoRubric(ctx);
                } else if (mode === GradingMode.Auto) {
                    // Auto mode + no rubric = Stop
                    console.log('[GradingView] 自动模式 + 无评分标准 = 停止');
                    setErrorMsg("未配置评分标准，自动阅卷停止");
                    setStatus('error');
                    stopAuto();
                } else {
                    setErrorMsg("请先配置评分标准");
                    setStatus('error');
                }
                return;
            }

            // Start Grading
            console.log('[GradingView] 开始批改，模式:', mode);
            if (mode === GradingMode.Auto) {
                startAutoGrading(ctx, currentRubric);
            } else {
                startAssistGrading(ctx, currentRubric);
            }
        });
    };

    const generateAutoRubric = async (ctx: PageContext) => {
        setIsGeneratingRubric(true);
        try {
            const rubric = await generateRubricFromImages(ctx.answerImageBase64 || null, null);
            setAutoGeneratedRubric(JSON.stringify(rubric));
        } catch (e) {
            console.error(e);
        } finally {
            setIsGeneratingRubric(false);
        }
    };

    /**
     * 通用批改执行函数
     * 职责：调用 AI 批改并返回标准化结果（含性能监控）
     * @returns StudentResult 或抛出异常
     */
    const executeGrading = async (
        ctx: PageContext,
        rubric: string,
        options?: { showStreamingText?: boolean }
    ): Promise<StudentResult> => {
        const startTime = performance.now();
        let result;

        // 检查是否使用代理模式（通过后端 API 批改）
        if (isProxyMode()) {
            console.log('[GradingView] 使用代理模式批改');
            if (options?.showStreamingText) {
                setStreamingText('正在通过云端 AI 批改…');
            }
            result = await gradeWithProxy(
                ctx.answerImageBase64 || '',
                rubric,
                ctx.studentName,
                manualQuestionNo || ctx.questionNo,
                gradingStrategy === 'flash' ? 'flash' : gradingStrategy === 'reasoning' ? 'reasoning' : 'pro',
                { questionKey: ctx.questionKey, examNo: ctx.examNo }
            );
        } else {
            // 前端直连模式（需要 API Key）
            console.log('[GradingView] 使用前端直连模式批改');
            if (options?.showStreamingText) {
                result = await gradeStudentAnswerStream(
                    ctx.answerImageBase64 || '',
                    rubric,
                    (chunk) => setStreamingText(prev => prev + chunk)
                );
            } else {
                result = await assessStudentAnswer(ctx.answerImageBase64 || '', rubric, gradingStrategy);
            }
        }

        // 性能监控：记录耗时
        const elapsedMs = Math.round(performance.now() - startTime);
        console.log(`[GradingView] ⏱️ 批改耗时: ${elapsedMs}ms (${(elapsedMs / 1000).toFixed(1)}s)`);

        // 标准化结果
        const normalizedBreakdown = normalizeBreakdown(result.breakdown as any, result.maxScore);
        return {
            id: Date.now().toString(),
            name: ctx.studentName || '考生',
            score: result.score,
            maxScore: result.maxScore,
            comment: result.comment || '',
            breakdown: normalizedBreakdown
        };
    };

    /**
     * 统一错误处理函数
     * 职责：解析错误类型，设置对应的错误信息，触发相关回调
     */
    const handleGradingError = (e: any, context: { stopOnError?: () => void } = {}) => {
        console.error('[GradingView] 批改错误:', e);

        // 额度不足错误
        if (e?.code === 'QUOTA_INSUFFICIENT' || e?.message?.includes('额度不足')) {
            setErrorMsg('额度不足，请激活充值后继续批改');
            onShowActivation?.();
        }
        // 超时错误
        else if (e?.message?.includes('超时') || e?.name === 'AbortError') {
            setErrorMsg('批改超时，请检查网络后重试');
        }
        // API Key 未配置
        else if (e?.message?.includes('API Key')) {
            setErrorMsg('请先配置 API Key 或使用云端批改');
        }
        // 通用错误
        else {
            setErrorMsg(e?.message || '阅卷失败，请重试');
        }

        setStatus('error');
        context.stopOnError?.();
    };

    /**
     * 自动模式批改入口
     * 职责：批改 → 自动填分提交 → 继续下一份
     */
    const startAutoGrading = async (ctx: PageContext, rubric: string) => {
        // 激活拦截检查
        if (checkActivationRequired()) {
            onShowActivation?.();
            stopAuto();
            return;
        }

        setStatus('grading');
        try {
            const finalResult = await executeGrading(ctx, rubric);

            setResult(finalResult);
            lastGradedSignatureRef.current = getAnswerSignature(ctx.answerImageBase64);

            // 自动模式：填分并提交
            fillScore(finalResult.score, true, finalResult);

            setAutoCount(c => c + 1);
            setStatus('review');

            // 延迟后继续下一份
            setTimeout(() => scanPage(), 1500);
        } catch (e: any) {
            handleGradingError(e, { stopOnError: stopAuto });
        }
    };

    /**
     * 辅助模式批改入口
     * 职责：批改 → 填分（不提交） → 等待用户确认
     */
    const startAssistGrading = async (ctx: PageContext, rubric: string) => {
        // 激活拦截检查
        if (checkActivationRequired()) {
            onShowActivation?.();
            return;
        }

        setStatus('grading');
        setStreamingText('');
        try {
            const finalResult = await executeGrading(ctx, rubric, { showStreamingText: true });

            setResult(finalResult);
            lastGradedSignatureRef.current = getAnswerSignature(ctx.answerImageBase64);
            setStatus('review');

            // 辅助模式：填分但不提交，等待用户确认
            if (isAssistLoopingRef.current) {
                fillScore(finalResult.score, false, finalResult);
                setAssistAwaitingConfirm(true);
                assistAwaitingConfirmRef.current = true;
            }
        } catch (e: any) {
            handleGradingError(e);
        }
    };

    const fillScore = (score: number, autoSubmit: boolean, resultToSave: StudentResult) => {
        // 1. Send to Page
        if (typeof chrome !== 'undefined' && chrome.tabs) {
            chrome.tabs.query({ active: true, currentWindow: true }, (tabs: chrome.tabs.Tab[]) => {
                if (tabs[0]?.id && pageContext?.platform) {
                    chrome.tabs.sendMessage(tabs[0].id, {
                        type: 'FILL_SCORE',
                        score: score,
                        platform: pageContext.platform,
                        options: { autoSubmit }
                    });
                }
            });
        }

        // 2. Save History (Unify storage key using record-sync)
        const histItem = {
            ...resultToSave,
            score,
            timestamp: Date.now(),
            questionNo: manualQuestionNo || pageContext?.questionNo || '?',
            platform: pageContext?.platform || 'MANUAL'
        };

        try {
            // 使用统一的 record-sync 服务保存，这会同步更新 localStorage['grading_records_v2']
            addLocalRecord(histItem as any);

            // 标记用户已使用过批改（用于首次使用检查）
            localStorage.setItem('has_graded_before', 'true');
        } catch (e) { console.error(e); }
    };

    // --- Loop Controls ---

    const startAuto = () => {
        if (!isRubricConfigured) return toast.warning("请先配置评分标准");
        setMode(GradingMode.Auto); // 设置为自动模式
        setIsAutoRunning(true);
        isAutoRunningRef.current = true;
        setAutoStartTime(Date.now());
        setAutoCount(0);
        scanPage({ forceStatusReset: true });
    };

    const stopAuto = () => {
        console.log('[GradingView] stopAuto 被调用');
        setIsAutoRunning(false);
        isAutoRunningRef.current = false;
        abortScanRef.current = true;
        setWaitCount(0);
        setStatus('idle');
        setMode(GradingMode.Auto); // 保持模式不变但重置状态
        console.log('[GradingView] stopAuto 完成: isAutoRunningRef =', isAutoRunningRef.current);
    };

    const startAssist = () => {
        if (!isRubricConfigured) return toast.warning("请先配置评分标准");
        setMode(GradingMode.Assist); // 确保设置为辅助模式
        setIsAssistLooping(true);
        isAssistLoopingRef.current = true;
        assistAwaitingConfirmRef.current = false;
        setAssistAwaitingConfirm(false);
        scanPage({ forceStatusReset: true });
    };

    const stopAssist = () => {
        setIsAssistLooping(false);
        isAssistLoopingRef.current = false;
        assistAwaitingConfirmRef.current = false;
        setAssistAwaitingConfirm(false);
        abortScanRef.current = true;
        setWaitCount(0); // 重置等待计数
        setStatus('idle');
    };

    const handleNextAssist = () => {
        // 1. 发送确认提交指令给网页 (补全关键的一脚)
        if (typeof chrome !== 'undefined' && chrome.tabs && result) {
            chrome.tabs.query({ active: true, currentWindow: true }, (tabs: chrome.tabs.Tab[]) => {
                if (tabs[0]?.id) {
                    chrome.tabs.sendMessage(tabs[0].id, {
                        type: 'SUBMIT_SCORE',
                        score: result.score
                    });
                }
            });
        }

        // 2. 稍微延迟重置状态，等待网页跳转
        setTimeout(() => {
            setAssistAwaitingConfirm(false);
            isAssistLoopingRef.current = true;
            assistAwaitingConfirmRef.current = false;
            setStatus('scanning');
            setResult(null);
            scanPage({ bypassLoopGuard: true });
        }, 500);
    };


    // --- Render ---

    // Computed state for UI
    const isReady = health.api && isRubricConfigured;
    const isRunning = isAutoRunning || isAssistLooping;

    return (
        <div className="flex flex-col h-full bg-gray-50/50 dark:bg-gray-900/50 relative font-sans">

            {/* --- Top Bar: Refined --- */}
            <div className="px-4 py-3 pb-2 flex items-center justify-between z-20 shrink-0 bg-white dark:bg-gray-900 border-b border-gray-50 dark:border-gray-800">
                {/* Mode Switch (Sub-toolbar style) */}
                <div className="flex items-center gap-2">
                    <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">模式</div>
                    <div className="flex bg-gray-100 dark:bg-gray-800 rounded-lg p-0.5 cursor-pointer shadow-inner">
                        <button
                            onClick={() => setMode(GradingMode.Assist)}
                            disabled={isRunning}
                            className={`px-3 py-1 rounded-md text-[11px] font-bold transition-all ${mode === GradingMode.Assist
                                ? 'bg-white dark:bg-gray-700 shadow-sm text-blue-600'
                                : 'text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
                                }
 ${isRunning ? 'opacity-50 cursor-not-allowed' : ''}`}
                        >
                            辅助
                        </button>
                        <button
                            onClick={() => setMode(GradingMode.Auto)}
                            disabled={isRunning}
                            className={`px-3 py-1 rounded-md text-[11px] font-bold transition-all ${mode === GradingMode.Auto
                                ? 'bg-white dark:bg-gray-700 shadow-sm text-emerald-600'
                                : 'text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
                                }
 ${isRunning ? 'opacity-50 cursor-not-allowed' : ''}`}
                        >
                            自动
                        </button>
                    </div>
                </div>

                {/* Question Selector Trigger */}
                <div className="flex items-center gap-2">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setShowQuestionDropdown(!showQuestionDropdown)}
                        icon={<ChevronDown className="w-3 h-3" />}
                        className="rounded-lg h-8 px-2.5 text-xs font-medium border-gray-200 dark:border-gray-700"
                    >
                        第 {manualQuestionNo || pageContext?.questionNo || '?'} 题
                    </Button>
                </div>
            </div>

            {/* Dropdown for Question (Absolute) */}
            {showQuestionDropdown && (
                <div className="absolute top-14 right-4 w-56 z-50 bg-white dark:bg-gray-800 rounded-xl shadow-xl border border-gray-100 dark:border-gray-700 p-2 animate-in fade-in slide-in-from-top-1">
                    <div className="text-[10px] uppercase text-gray-400 font-bold px-2 py-1">选择或输入题号</div>
                    {configuredQuestions.map(q => (
                        <button
                            key={q.key}
                            onClick={() => {
                                setManualQuestionNo(q.questionNo);
                                const pureKey = q.key.replace('app_rubric_content:', '');
                                setDetectedQuestionKey(pureKey);
                                if (onQuestionKeyChange) onQuestionKeyChange(pureKey);
                                setShowQuestionDropdown(false);
                            }}
                            className="w-full text-left px-3 py-2 text-xs rounded-lg hover:bg-blue-50 dark:hover:bg-blue-900/20 text-gray-700 dark:text-gray-300 flex justify-between"
                        >
                            <span>第 {q.questionNo} 题</span>
                            <span className="text-[10px] opacity-50">{q.platform}</span>
                        </button>
                    ))}

                    <div className="border-t border-gray-100 dark:border-gray-700 my-1"></div>

                    <div className="flex gap-2 p-1">
                        <input
                            aria-label="题号"
                            className="flex-1 min-w-0 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-2 py-1 text-xs outline-none focus:border-blue-500"
                            placeholder="题号…"
                            value={manualQuestionNo}
                            onChange={e => setManualQuestionNo(e.target.value)}
                        />
                        <Button
                            variant="primary"
                            size="sm"
                            onClick={() => setShowQuestionDropdown(false)}
                        >
                            确定
                        </Button>
                    </div>
                </div>
            )}

            {/* --- Main Content Stage --- */}
            <div className="flex-1 relative overflow-y-auto overflow-x-hidden p-4 pb-24 scrollbar-thin">

                {/* Status Overlay: Display when not reviewing result */}
                {status !== 'review' && (
                    <div className="h-full flex flex-col items-center justify-center animate-fade-in">
                        {status === 'idle' && waitCount === 0 && (
                            <div className="text-center space-y-4 max-w-[320px]">
                                {/* 评分细则库 - 在 API 和页面正常时始终显示 */}
                                {health.api && health.pageLink && (
                                    <RubricLibrary
                                        selectedKey={detectedQuestionKey}
                                        onSelect={(key) => {
                                            const parts = key.split(':');
                                            const questionNo = parts[parts.length - 1] || '?';
                                            setManualQuestionNo(questionNo);
                                            setDetectedQuestionKey(key);
                                            if (onQuestionKeyChange) onQuestionKeyChange(key);
                                        }}
                                        onNew={onOpenRubric}
                                        onImport={onOpenRubric}
                                        onEdit={onOpenRubric}
                                        defaultExpanded={!isRubricConfigured}
                                        className="mb-4 text-left"
                                    />
                                )}

                                {/* 完全就绪状态 */}
                                {health.api && health.pageLink && isRubricConfigured ? (
                                    <>
                                        {/* 答题卡需要刷新提示 */}
                                        {answerCardStatus?.status === 'needRefresh' && (
                                            <div className="mb-4 p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700 rounded-xl">
                                                <div className="flex items-center gap-2 text-amber-700 dark:text-amber-400">
                                                    <AlertCircle className="w-5 h-5 shrink-0" />
                                                    <div>
                                                        <p className="text-sm font-medium">答题卡需要刷新</p>
                                                        <p className="text-xs text-amber-600 dark:text-amber-500 mt-0.5">
                                                            请按 F5 或点击页面刷新按钮
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        )}
                                        {/* 答题卡加载中提示 */}
                                        {answerCardStatus?.status === 'loading' && (
                                            <div className="mb-4 p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 rounded-xl">
                                                <div className="flex items-center gap-2 text-blue-700 dark:text-blue-400">
                                                    <Loader className="w-5 h-5 shrink-0 animate-spin" />
                                                    <p className="text-sm">答题卡正在加载中…</p>
                                                </div>
                                            </div>
                                        )}
                                        <div className="w-16 h-16 mx-auto bg-gradient-to-tr from-green-100 to-emerald-100 dark:from-green-900/20 dark:to-emerald-900/20 rounded-full flex items-center justify-center mb-4 shadow-float">
                                            <Zap className="w-8 h-8 text-green-600 dark:text-green-400" />
                                        </div>
                                        <h2 className="text-base font-bold text-gray-900 dark:text-white">准备就绪</h2>
                                        <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed">
                                            点击下方按钮开始阅卷
                                        </p>
                                    </>
                                ) : (
                                    <>
                                        {/* 检测中/需要配置状态 */}
                                        <div className={`w-20 h-20 mx-auto rounded-full flex items-center justify-center mb-4 shadow-float relative ${isDetecting
                                            ? 'bg-gradient-to-tr from-blue-100 to-cyan-100 dark:from-blue-900/20 dark:to-cyan-900/20'
                                            : 'bg-gradient-to-tr from-amber-100 to-orange-100 dark:from-amber-900/20 dark:to-orange-900/20'
                                            }`}>
                                            {isDetecting && (
                                                <div className="absolute inset-0 rounded-full border-4 border-blue-500/30 border-t-blue-500 animate-spin"></div>
                                            )}
                                            {isDetecting ? (
                                                <ScanLine className="w-10 h-10 text-blue-600 dark:text-blue-400" />
                                            ) : (
                                                <AlertCircle className="w-10 h-10 text-amber-600 dark:text-amber-400" />
                                            )}
                                        </div>
                                        <div className="flex items-center justify-center gap-2">
                                            <h2 className="text-lg font-bold text-gray-900 dark:text-white">
                                                {isDetecting ? '正在检测...' : '请完成配置'}
                                            </h2>
                                            {!isDetecting && (
                                                <Button
                                                    variant="ghost"
                                                    size="sm"
                                                    onClick={checkSystemHealth}
                                                    icon={<RefreshCw className="w-4 h-4" />}
                                                    className="p-1.5 rounded-lg text-gray-400 hover:text-blue-500"
                                                    title="重新检测"
                                                >
                                                    <span className="sr-only">重新检测</span>
                                                </Button>
                                            )}
                                        </div>

                                        {/* 配置检查清单 */}
                                        <div className="space-y-2 text-left bg-white/80 dark:bg-gray-800/80 rounded-xl p-3 border border-gray-100 dark:border-gray-700">
                                            {/* API 连接状态 */}
                                            <div
                                                className={`flex items-center gap-2 p-2 rounded-lg transition-all duration-300 ${detectingStep < 1
                                                    ? 'bg-gray-50 dark:bg-gray-700/50'
                                                    : health.api
                                                        ? 'bg-green-50 dark:bg-green-900/20'
                                                        : 'bg-red-50 dark:bg-red-900/20 hover:bg-red-100 cursor-pointer'
                                                    }`}
                                                onClick={() => detectingStep >= 1 && !health.api && onOpenSettings()}
                                            >
                                                <div className={`w-5 h-5 rounded-full flex items-center justify-center transition-all duration-300 ${detectingStep < 1 ? 'bg-gray-300' : health.api ? 'bg-green-500' : 'bg-red-500'
                                                    }`}>
                                                    {detectingStep < 1 ? (
                                                        <div className="w-2 h-2 rounded-full bg-white animate-pulse"></div>
                                                    ) : health.api ? (
                                                        <Check className="w-3 h-3 text-white" />
                                                    ) : (
                                                        <X className="w-3 h-3 text-white" />
                                                    )}
                                                </div>
                                                <div className="flex-1">
                                                    <p className={`text-xs font-medium transition-colors ${detectingStep < 1 ? 'text-gray-500' : health.api ? 'text-green-700' : 'text-red-700'
                                                        }`}>
                                                        API 连接
                                                    </p>
                                                    <p className="text-[10px] text-gray-500">
                                                        {detectingStep < 1 ? '检测中...' : health.api ? '已连接' : '点击前往设置'}
                                                    </p>
                                                </div>
                                            </div>

                                            {/* 答题卡定位状态 */}
                                            <div className={`flex items-center gap-2 p-2 rounded-lg transition-all duration-300 ${detectingStep < 2
                                                ? 'bg-gray-50 dark:bg-gray-700/50'
                                                : health.pageLink ? 'bg-green-50 dark:bg-green-900/20' : 'bg-amber-50 dark:bg-amber-900/20'
                                                }`}>
                                                <div className={`w-5 h-5 rounded-full flex items-center justify-center transition-all duration-300 ${detectingStep < 2 ? 'bg-gray-300' : health.pageLink ? 'bg-green-500' : 'bg-amber-500'
                                                    }`}>
                                                    {detectingStep < 2 ? (
                                                        <div className="w-2 h-2 rounded-full bg-white animate-pulse"></div>
                                                    ) : health.pageLink ? (
                                                        <Check className="w-3 h-3 text-white" />
                                                    ) : (
                                                        <span className="text-[10px] text-white font-bold">!</span>
                                                    )}
                                                </div>
                                                <div className="flex-1">
                                                    <p className={`text-xs font-medium transition-colors ${detectingStep < 2 ? 'text-gray-500' : health.pageLink ? 'text-green-700' : 'text-amber-700'
                                                        }`}>
                                                        答题卡定位
                                                    </p>
                                                    <p className="text-[10px] text-gray-500">
                                                        {detectingStep < 2 ? '检测中...' : health.pageLink ? '已定位' : '请打开阅卷页面'}
                                                    </p>
                                                </div>
                                            </div>

                                            {/* 评分细则状态 */}
                                            <div
                                                className={`flex items-center gap-2 p-2 rounded-lg transition-all duration-300 ${detectingStep < 3
                                                    ? 'bg-gray-50 dark:bg-gray-700/50'
                                                    : isRubricConfigured ? 'bg-green-50 dark:bg-green-900/20' : 'bg-amber-50 dark:bg-amber-900/20 hover:bg-amber-100 cursor-pointer'
                                                    }`}
                                                onClick={() => detectingStep >= 3 && !isRubricConfigured && onOpenRubric()}
                                            >
                                                <div className={`w-5 h-5 rounded-full flex items-center justify-center transition-all duration-300 ${detectingStep < 3 ? 'bg-gray-300' : isRubricConfigured ? 'bg-green-500' : 'bg-amber-500'
                                                    }`}>
                                                    {detectingStep < 3 ? (
                                                        <div className="w-2 h-2 rounded-full bg-white animate-pulse"></div>
                                                    ) : isRubricConfigured ? (
                                                        <Check className="w-3 h-3 text-white" />
                                                    ) : (
                                                        <span className="text-[10px] text-white font-bold">!</span>
                                                    )}
                                                </div>
                                                <div className="flex-1">
                                                    <p className={`text-xs font-medium transition-colors ${detectingStep < 3 ? 'text-gray-500' : isRubricConfigured ? 'text-green-700' : 'text-amber-700'
                                                        }`}>
                                                        评分细则
                                                    </p>
                                                    <p className="text-[10px] text-gray-500">
                                                        {detectingStep < 3 ? '检测中...' : isRubricConfigured ? '已配置' : '点击配置评分标准'}
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </>
                                )}
                            </div>
                        )}

                        {(status === 'scanning' || waitCount > 0) && (
                            <div className="text-center space-y-4 max-w-[240px]">
                                <div className={`w-20 h-20 mx-auto rounded-full flex items-center justify-center mb-6 shadow-float relative ${waitingRefresh
                                    ? 'bg-gradient-to-tr from-amber-100 to-orange-100 dark:from-amber-900/20 dark:to-orange-900/20'
                                    : 'bg-gradient-to-tr from-blue-100 to-cyan-100 dark:from-blue-900/20 dark:to-cyan-900/20'
                                    }`}>
                                    {!waitingRefresh && (
                                        <div className="absolute inset-0 rounded-full border-4 border-blue-500/30 border-t-blue-500 animate-spin"></div>
                                    )}
                                    {waitingRefresh ? (
                                        <RefreshCw className="w-10 h-10 text-amber-600 dark:text-amber-400" />
                                    ) : (
                                        <ScanLine className="w-10 h-10 text-blue-600 dark:text-blue-400" />
                                    )}
                                </div>
                                {waitingRefresh ? (
                                    <>
                                        <h2 className="text-lg font-bold text-amber-700 dark:text-amber-400">请刷新阅卷界面</h2>
                                        <p className="text-xs text-amber-600 dark:text-amber-500 leading-relaxed">
                                            页面未自动跳转到下一张试卷<br />
                                            请按 F5 或点击页面刷新按钮
                                        </p>
                                        <p className="text-[10px] text-gray-400 mt-2">
                                            刷新后将自动继续阅卷
                                        </p>
                                    </>
                                ) : (
                                    <>
                                        <h2 className="text-lg font-bold text-gray-900 dark:text-white">正在扫描试卷...</h2>
                                        <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed">
                                            {waitCount > 2 ? "页面响应较慢，请稍候…" : "正在分析当前页面内容"}
                                        </p>
                                    </>
                                )}
                            </div>
                        )}

                        {status === 'grading' && (
                            <div className="w-full max-w-xs">
                                <div className="bg-white/90 dark:bg-gray-800/90 backdrop-blur-xl rounded-2xl shadow-xl border border-white/20 dark:border-gray-700 p-6">
                                    <div className="flex justify-center mb-6">
                                        <div className="relative">
                                            <div className="absolute inset-0 bg-purple-500 blur-xl opacity-20 animate-pulse"></div>
                                            <Microscope className="w-12 h-12 text-purple-600 dark:text-purple-400 relative z-10 animate-bounce-slow" />
                                        </div>
                                    </div>
                                    <div className="space-y-4">
                                        <h3 className="text-center font-bold text-gray-800 dark:text-white">AI 智能批改中</h3>
                                        <div className="space-y-2">
                                            {['提取答卷信息', '分析解题思路', '匹配评分标准', '生成评价反馈'].map((step, i) => (
                                                <div key={i} className="flex items-center gap-3">
                                                    <div className={`w-2 h-2 rounded-full transition-colors duration-300 ${i <= gradingStep ? 'bg-purple-500 shadow-[0_0_8px_rgba(168,85,247,0.5)]' : 'bg-gray-200 dark:bg-gray-700'}`}></div>
                                                    <span className={`text-xs transition-colors duration-300 ${i <= gradingStep ? 'text-gray-800 dark:text-gray-200 font-medium' : 'text-gray-400'}`}>{step}</span>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        )}

                        {status === 'error' && (
                            <div className="text-center space-y-4 max-w-[240px] animate-shake">
                                <div className="w-20 h-20 mx-auto bg-gradient-to-tr from-red-100 to-orange-100 dark:from-red-900/20 dark:to-orange-900/20 rounded-full flex items-center justify-center mb-6 shadow-float">
                                    <AlertCircle className="w-10 h-10 text-red-600 dark:text-red-400" />
                                </div>
                                <h2 className="text-lg font-bold text-gray-900 dark:text-white">发生错误</h2>
                                <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed">
                                    {errorMsg || "请检查网络或重试"}
                                </p>
                            </div>
                        )}
                    </div>
                )}

                {/* Result View */}
                {status === 'review' && result && (
                    <div className="animate-slide-up pb-8 space-y-4">
                        {/* Assist Mode Confirmation Hint */}
                        {mode === GradingMode.Assist && assistAwaitingConfirm && (
                            <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-800 p-3 rounded-xl flex items-center justify-between gap-2 shadow-sm animate-pulse-subtle">
                                <div className="flex items-center gap-2 text-amber-800 dark:text-amber-200 text-xs font-medium">
                                    <Pause className="w-4 h-4 fill-current" />
                                    <span>请确认分数并录入</span>
                                </div>
                            </div>
                        )}

                        {/* Main Score Card */}
                        <div className={`
                    relative overflow-hidden rounded-3xl p-6 text-white shadow-2xl transition-transform duration-500
                    ${mode === GradingMode.Auto ? 'bg-gradient-to-br from-emerald-500 to-teal-700' : 'bg-gradient-to-br from-blue-600 to-violet-700'}
                  `}>
                            {/* Decorative Background */}
                            <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
                            <div className="absolute bottom-0 left-0 w-24 h-24 bg-black/10 rounded-full blur-2xl -ml-12 -mb-12 pointer-events-none"></div>

                            <div className="relative z-10 flex justify-between items-start">
                                <div>
                                    <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-md bg-white/20 border border-white/10 backdrop-blur-md mb-2">
                                        {mode === GradingMode.Auto ? <Bot className="w-3 h-3" /> : <MousePointerClick className="w-3 h-3" />}
                                        <span className="text-[10px] font-bold tracking-wider uppercase">{mode === GradingMode.Auto ? '自动模式' : '辅助模式'}</span>
                                    </div>
                                    <h1 className="text-2xl font-bold tracking-tight">
                                        {pageContext?.studentName || "考生"}
                                    </h1>
                                    <p className="text-white/70 text-xs mt-1 font-medium">
                                        {pageContext?.examNo ? `考号: ${pageContext.examNo}` : (mode === GradingMode.Auto ? `已处理 ${autoCount} 份` : '等待确认')}
                                    </p>
                                </div>

                                <div className="text-right">
                                    <div className="flex items-baseline justify-end gap-1">
                                        {isEditingScore ? (
                                            <input
                                                autoFocus
                                                type="number"
                                                className="w-24 bg-white/20 border border-white/30 rounded-lg text-4xl font-black text-center text-white outline-none"
                                                value={editableScore ?? result.score}
                                                onChange={e => setEditableScore(Number(e.target.value))}
                                                onBlur={() => {
                                                    if (editableScore !== null) {
                                                        const newRes = { ...result, score: editableScore };
                                                        setResult(newRes);
                                                        fillScore(editableScore, false, newRes);
                                                    }
                                                    setIsEditingScore(false);
                                                }}
                                                onKeyDown={e => e.key === 'Enter' && setIsEditingScore(false)}
                                            />
                                        ) : (
                                            <span
                                                onClick={() => { setEditableScore(result.score); setIsEditingScore(true); }}
                                                className="text-5xl font-black tracking-tighter cursor-pointer hover:scale-105 transition-transform"
                                            >
                                                {result.score}
                                            </span>
                                        )}
                                        <span className="text-lg text-white/60 font-medium">/{result.maxScore}</span>
                                    </div>
                                    {result.score === result.maxScore && (
                                        <div className="flex items-center justify-end gap-1 text-yellow-300 text-xs font-bold mt-1">
                                            <Sparkles className="w-3 h-3" /> 满分
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>

                        {/* Breakdown List */}
                        <div className="space-y-3">
                            <div className="flex items-center gap-2 px-1">
                                <ListChecks className="w-4 h-4 text-gray-400" />
                                <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">得分详情</span>
                            </div>

                            {result.breakdown.map((item, idx) => {
                                const isFull = item.score === item.max;
                                const isZero = item.score === 0;

                                return (
                                    <div key={idx} className="bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-100 dark:border-gray-700 shadow-sm transition-all hover:shadow-md">
                                        <div className="flex justify-between items-center mb-2">
                                            <div className="flex items-center gap-2">
                                                <div className={`w-1.5 h-1.5 rounded-full ${isFull ? 'bg-green-500' : (isZero ? 'bg-red-500' : 'bg-orange-500')}`}></div>
                                                <span className="text-sm font-bold text-gray-800 dark:text-gray-200">{item.label}</span>
                                            </div>
                                            <div className={`px-2 py-0.5 rounded-md text-xs font-bold font-mono ${isFull ? 'bg-green-50 text-green-600 dark:bg-green-900/20 dark:text-green-400' :
                                                (isZero ? 'bg-red-50 text-red-600 dark:bg-red-900/20 dark:text-red-400' : 'bg-orange-50 text-orange-600 dark:bg-orange-900/20 dark:text-orange-400')
                                                }`}>
                                                {item.score} / {item.max}
                                            </div>
                                        </div>

                                        {/* Reason */}
                                        <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed pl-3.5 border-l-2 border-gray-100 dark:border-gray-700">
                                            {item.comment || (isFull ? "回答正确，符合标准" : "未达到标准要求")}
                                        </p>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                )}
            </div>

            {/* --- Bottom Action Bar --- */}
            <div className="p-4 pt-2 bg-gradient-to-t from-white via-white to-transparent dark:from-gray-900 dark:via-gray-900 z-10">
                <div className="flex items-center gap-3">
                    {/* Mode Switch (Small) */}
                    <div className="flex bg-gray-100 dark:bg-gray-800 p-1 rounded-xl shrink-0">
                        <button
                            onClick={() => setMode(GradingMode.Assist)}
                            title="辅助模式 (人工确认)"
                            className={`p-2 rounded-lg transition-all ${mode === GradingMode.Assist ? 'bg-white dark:bg-gray-700 shadow-sm text-blue-600' : 'text-gray-400 hover:text-gray-600'}`}
                        >
                            <MousePointerClick className="w-5 h-5" />
                        </button>
                        <button
                            onClick={() => setMode(GradingMode.Auto)}
                            title="自动模式 (全自动)"
                            className={`p-2 rounded-lg transition-all ${mode === GradingMode.Auto ? 'bg-white dark:bg-gray-700 shadow-sm text-emerald-600' : 'text-gray-400 hover:text-gray-600'}`}
                        >
                            <Bot className="w-5 h-5" />
                        </button>
                    </div>

                    {/* Main Action Button */}
                    {isRunning ? (
                        mode === GradingMode.Assist && assistAwaitingConfirm ? (
                            <>
                                {/* 辅助模式：等待确认状态 - 显示停止和继续两个按钮 */}
                                <button
                                    onClick={stopAssist}
                                    className="shrink-0 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium h-12 px-4 rounded-xl transition-all active:scale-95 flex items-center justify-center gap-2"
                                >
                                    <Square className="w-4 h-4" />
                                    <span>停止</span>
                                </button>
                                <button
                                    onClick={handleNextAssist}
                                    className="flex-1 bg-gradient-to-r from-blue-600 to-violet-600 hover:from-blue-700 hover:to-violet-700 text-white font-bold h-12 rounded-xl shadow-lg shadow-blue-500/30 transition-all active:scale-95 flex items-center justify-center gap-2"
                                >
                                    <span>继续下一份</span>
                                    <Play className="w-5 h-5 fill-current" />
                                </button>
                            </>
                        ) : (
                            <button
                                onClick={mode === GradingMode.Auto ? stopAuto : stopAssist}
                                className="flex-1 bg-red-500 hover:bg-red-600 text-white font-bold h-12 rounded-xl shadow-lg shadow-red-500/30 transition-all active:scale-95 flex items-center justify-center gap-2"
                            >
                                <Square className="w-4 h-4 fill-current" />
                                <span>停止{mode === GradingMode.Auto ? '自动' : '辅助'}模式</span>
                                {mode === GradingMode.Auto && <span className="text-xs opacity-80 font-mono ml-1">{elapsedSeconds}s</span>}
                            </button>
                        )
                    ) : (
                        <button
                            onClick={mode === GradingMode.Auto ? startAuto : startAssist}
                            disabled={!isReady}
                            className={`
                          flex-1 font-bold h-12 rounded-xl shadow-lg transition-all active:scale-95 flex items-center justify-center gap-2
                          ${isReady
                                    ? (mode === GradingMode.Auto
                                        ? 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-500/30'
                                        : 'bg-blue-600 hover:bg-blue-700 text-white shadow-blue-500/30')
                                    : 'bg-gray-200 text-gray-400 cursor-not-allowed dark:bg-gray-800 dark:text-gray-600'
                                }
                      `}
                        >
                            <Play className="w-5 h-5 fill-current" />
                            <span>开始{mode === GradingMode.Auto ? '自动' : '辅助'}阅卷</span>
                        </button>
                    )}


                </div>
            </div>

            {/* Auto Rubric Modal Overlay */}
            <AutoRubricModal
                isOpen={showAutoRubricModal}
                isLoading={isGeneratingRubric}
                rubricContent={autoGeneratedRubric}
                questionNo={manualQuestionNo || pageContext?.questionNo || '?'}
                onConfirm={() => {
                    if (onSaveRubric) onSaveRubric(autoGeneratedRubric);
                    setShowAutoRubricModal(false);
                    setAutoGeneratedRubric('');
                }}
                onEdit={() => {
                    setShowAutoRubricModal(false);
                    onOpenRubric();
                }}
                onSkip={() => {
                    setShowAutoRubricModal(false);
                }}
            />

        </div>
    );
};

export default GradingView;
